name: Auto Update HF Space

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Clone HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://Renegade44:${HF_TOKEN}@huggingface.co/spaces/Renegade44/AIOstreams hf_repo

      - name: Copy all files
        run: |
          cp -r * hf_repo/

      - name: Commit and push
        run: |
          cd hf_repo
          git config user.email "bot@example.com"
          git config user.name "bot"

          git add .
          git commit -m "auto update" || echo "no changes"
          git push
